apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: sumairasaifee/backend:065fc92e2cf245f52997e5f43d551c0784bb1eb3
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
