apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
  labels:
    app: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: nginx
        image: sumairasaifee/backend:3e9597ab3c38a876399e53022b075cb9851a6f9b
        imagePullPolicy: Always
        ports:
        - containerPort: 5000
