apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: sumairasaifee/frontend:2c860c903c10f10516e7ad4557d1f81a6d45bdea
        imagePullPolicy: Always
        ports:
        - containerPort: 80
