apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: sumairasaifee/frontend:ba4ed1adb44656754f70d31bba91b973c4627d54
        imagePullPolicy: Always
        ports:
        - containerPort: 80
