apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: nginx
        image: sumairasaifee/frontend:065fc92e2cf245f52997e5f43d551c0784bb1eb3
        imagePullPolicy: Always
        ports:
        - containerPort: 80
